### ISSUE TITLE
plotting dot file

### ISSUE THREAD

**Issue by k3yavi** [rchikhi/python-bcalm#2]
[compacted.dot.zip](https://github.com/rchikhi/python-bcalm/files/626352/compacted.dot.zip)
Can you please help me in plotting above attached dot file generated by bcalm run.

The usual dot command gives the following error:
```
╰─$ dot -Tpdf compacted.dot > output.pdf
Error: compacted.dot: syntax error in line 1 near 'aaagtgtctgaattttctgactcttcccgtc'
```

**Comment by rchikhi** [comment]
Hi, the .dot files in bcalm1 (and python-bcalm, this repository) are a misnomer: they look like GraphViz's DOT files but they do not contain any links. Thus, those cannot be plotted.
This is because bcalm1 outputs unitigs but does keep track of the graph edges in the output.

**Comment by rchikhi** [comment]
If you're interested in the unitigs graph, I suggest that you use BCALM2 (https://github.com/GATB/bcalm) along with the convertToGFA.py script. The GFA graph can then be plotted using Bandage (https://github.com/rrwick/Bandage).

**Comment by k3yavi** [comment]
@rchikhi Thanks! I used sga (which I think internally use Bcalm2) and generated `asqz` file to use in bandage. 
To summarize I did found a workaround, Thanks for your reply.
